image: golang:1.13

variables:
  DOCKER_NAME: postgresai/joe

cache:
  paths:
    - /apt-cache
    - /go/pkg/mod/cache

stages:
  - test
  - build-binary
  - build-image

test:
  before_script:
    - go mod download
  stage: test
  script:
    - make vet
    - make test

build-binary:
  stage: build-binary
  only:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - bin
  script:
    - make build

build-image:
  only:
    refs:
      - 18-dockerize-joe
      - tags
  image: docker:19
  stage: build-image
  variables:
    LATEST: latest
    CURRENT: todo
  artifacts:
    paths:
      - bin
  services:
    - docker:dind
  script:
    - set -x #TODO: Remove before merge.

    - TAG_LATEST="${DOCKER_NAME}:latest"
    - TAG_VERSION="${DOCKER_NAME}:${CI_COMMIT_TAG}"

    - docker login --username $DH_CI_REGISTRY_USER --password "${DH_CI_REGISTRY_PASSWORD}" $DH_CI_REGISTRY
    - docker build --tag $TAG_VERSION --tag $TAG_LATEST .

    - docker push $TAG_VERSION
    - docker push $TAG_LATEST
