image: golang:1.13

cache:
  paths:
    - /apt-cache
    - /go/pkg/mod/cache

before_script:
  - go mod download

stages:
  - test
  - build-binary
#  - build-image

test:
  stage: test
  script:
    - make vet
    - make test

build-binary:
  stage: build-binary
  only:
    refs:
      - 18-dockerize-joe #TODO(akartasov): Change to "master" before merge.
      - tags
  artifacts:
    paths:
      - bin
  script:
    - make build
