# Copy the following to: ./config/config.yml
# Joe Bot configuration.

app:
  # HTTP server port.
  port: 3001

  # Time interval to notify a user about the finish of a long query.
  minNotifyDuration: 60s

  # Enable a debug mode.
  debug: false

platform:
  # The Postgres.ai Platform API base URL.
  url: "https://postgres.ai/api/general"

  # The Postgres.ai Platform API token.
  token: ""

  # The Postgres.ai Platform project to assign user sessions.
  project: ""

  # Enable sending command and queries history to the Postgres.ai Platform for collaboration and visualization.
  historyEnabled: false

# Channel Mapping section.
# Feel free to choose any name for Database Lab instances from the `dblabServers` section those are just aliases.
channelMapping:
  communicationTypes:
    slack:
      - name: Workspace
        credentials:
          accessToken: access_token
          signingSecret: secret_signing
        channels:
          - channelID: channelID1
            dblabServer: prod1
            dblabParams:
              dbname: postgres
              sslmode: disable
    webui:
      - name: WebUI
        credentials:
          signingSecret: secret_signing
        channels:
          - channelID: channelID1
            dblabServer: prod1
            dblabParams:
              dbname: postgres
              sslmode: disable

  dblabServers:
    prod1:
      url: "https://127.0.0.1:3000"
      token: "secret_token"

# Enterprise options (changing these options you confirm that you have active
# subscription to Postgres.ai Platform Enterprise Edition https://postgres.ai).
enterprise:
  quota:
    # Limit request rates.
    limit: 10

    # Time interval (in seconds) to apply a quota limit.
    interval: 60

  audit:
    # Enable logging of received commands.
    enabled: false

  dblab:
    # Limit available Database Lab instances.
    instanceLimit: 1
