# Copy the following to: ./config/config.yml
# Joe Bot configuration.

app:
  # HTTP server port.
  port: 3001

  # Time interval to notify a user about the finish of a long query.
  minNotifyDuration: 60s

  # Enable a debug mode.
  debug: false

platform:
  # The Postgres.ai Platform API base URL.
  url: "https://postgres.ai/api/general"

  # The Postgres.ai Platform API token.
  token: ""

  # The Postgres.ai Platform project to assign user sessions.
  project: ""

  # Enable sending command and queries history to the Postgres.ai Platform for collaboration and visualization.
  historyEnabled: false

# Channel Mapping section.
channelMapping:
  # Available communication types (Web UI, Slack, etc.)
  communicationTypes:
    # Web UI communication type configuration.
    webui:
      # Web UI name. Feel free to choose any name.
      - name: WebUI
        credentials:
          # WEB UI signing secret.
          signingSecret: secret_signing

        channels:
          # Web UI channel ID. Feel free to choose any name.
          - channelID: ProductionDB

            # Database Lab alias from the dblabServers section.
            dblabServer: prod1

            # Database Lab clone parameters.
            dblabParams:
              dbname: postgres
              sslmode: disable

    # Slack communication type configuration.
    slack:
      # Workspace name. Feel free to choose any name.
      - name: Workspace
        credentials:
          # Bot User OAuth Access Token ("xoxb-TOKEN").
          accessToken: access_token

          # Slack App Signing Secret.
          signingSecret: secret_signing

        channels:
          # Slack channel ID.
          - channelID: CXXXXXXX0

            # Database Lab alias from the dblabServers section.
            dblabServer: prod1

            # Database Lab clone parameters.
            dblabParams:
              dbname: postgres
              sslmode: disable

  # Running Database Lab instances.
  dblabServers:
    # Database Lab instance alias.
    prod1:
      url: "https://127.0.0.1:3000"
      token: "secret_token"

# Enterprise options (changing these options you confirm that you have active
# subscription to Postgres.ai Platform Enterprise Edition https://postgres.ai).
enterprise:
  quota:
    # Limit request rates.
    limit: 10

    # Time interval (in seconds) to apply a quota limit.
    interval: 60

  audit:
    # Enable logging of received commands.
    enabled: false

  dblab:
    # Limit available Database Lab instances.
    instanceLimit: 1
