communicationTypes:
  slack:
    - name: Workspace
      credentials:
        accessToken: access_token
        signingSecret: secret_signing
      channels:
        - channelID: channelID1
          dblabServer: prod1
          dblabParams:
            - dbname: postgres
              sslmode: disable
  webui:
    - name: WebUI
      credentials:
        signingSecret: secret_signing
      channels:
        - channelID: channelID1
          dblabServer: prod1
          dblabParams:
            - dbname: postgres
              sslmode: disable

dblabServers:
  prod1:
    url: "https://127.0.0.1:3000"
    token: "secret_token"
