connections:
  slack:
    - name: Workspace
      credentials:
        accessToken: access_token
        signingSecret: secret_signing
      channels:
        - channelID: channelID1
          dblab: prod1
  webui:
    - name: WebUI
      credentials:
        signingSecret: secret_signing
      channels:
        - channelID: channelID1
          dblab: prod1

dblabs:
  prod1:
    url: "https://127.0.0.1:3000"
    token: "secret_token"
    dbname: postgres
    sslmode: disable
