# 2019 © Postgres.ai

# Meta information and params for Joe's tips.

params:
  buffersReadBigMax: 100
  buffersHitBigMax: 1000
tips:
  - code: "SEQSCAN_USED"
    name: "SeqScan is used"
    description: "Consider adding an index"
    detailsUrl: "https://blog.makandra.com/2016/03/postgresql-query-optimization/"
  - code: "BUFFERS_READ_BIG"
    name: "Query processes too much data to return a few rows (read)"
    description: "Reduce data cardinality as early as possible during the execution"
    detailsUrl: "http://momjian.us/main/writings/pgsql/hw_performance/"
  - code: "BUFFERS_HIT_BIG"
    name: "Query processes too much data to return a few rows (hit)"
    description: "Reduce data cardinality as early as possible during the execution"
    detailsUrl: "http://momjian.us/main/writings/pgsql/hw_performance/"
