# 2019 © Postgres.ai

awsConfiguration:
  awsKeyName: "awskey3"
  awsKeyPath: "/home/xxx/.ssh/xxx.pem"
  awsInstanceType: "i3.large"
  awsRegion: "us-east-1"
  awsZone: "a"
  awsBlockDurationMinutes: 60
ebsVolumeId: "vol-xxx"
debug: true
pgVersion: "9.6"
initialSnapshot: "db_state_1"
