# Copy the following to: ./config/provisioning.yaml

mode: "mulocal"
mulocal:
  portPool:
    from: 6000
    to: 6100
debug: true
pgVersion: "11"
pgBindir: "/usr/lib/postgresql/9.6/bin/pg_ctl"
pgDataSubdir: "/pgdata"
zfsPool: "joepool"
initialSnapshot: "db_state_1"
